version: "3"

services:
    snowball:
        image: hyukkyukang/snowball:latest
        stdin_open: true
        tty: true
        network_mode: "host"
        volumes:
            - .:/home/snowball
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
